Update spell check GHA and use_spell_check() with configurable inputs
* feat(spell-check.yml): allow users to run spell check on specific file
  types
  * supported file types: .cpp, .hpp, .md, .R, .Rmd, .txt, and .yml
  * users can specify whether spelling errors should be reported as a
    warning or an error
* feat(use_spell_check()): add extra parameters to control spell check
  report level
* test(test-use_r_workflows.R): add additoinal tests and snapshot files
  for use_spell_check()
* fix(typos): use spelling::spell_check_files() to detect and correct
  typos

diff --git a/.github/workflows/spell-check.yml b/.github/workflows/spell-check.yml
--- a/.github/workflows/spell-check.yml
+++ b/.github/workflows/spell-check.yml
@@ -1,6 +1,17 @@
 # check spelling using spelling::spell_check_package()
 on:
  workflow_call:
+  inputs:
+    use_full_spell_check:
+      description: 'Whether to run a full spell check on selected files'
+      required: false
+      type: boolean
+      default: false
+    full_check_report_level:
+      description: 'The message level to report if spelling issues are found during the full spell check'
+      required: false
+      type: string
+      default: 'warning'
 
 name: run devtools::spell_check
 
@@ -26,13 +37,53 @@ jobs:
       - name: Install spelling
         run: Rscript -e 'install.packages("spelling")'
 
-      - name: spell check
+      - name: spell check using spelling::spell_check_package()
         run: |
           results <- spelling::spell_check_package()
           if(nrow(results)>0) {
             print(results)
-            stop("Spelling errors found.\n", 
-            "Need to ignore some words? Read up on using the WORDLIST file:\n",
-            "https://docs.ropensci.org/spelling/reference/wordlist.html")
+            stop(
+              "Spelling errors found.\n", 
+              "Need to ignore some words? Read up on using the WORDLIST file:\n",
+              "https://docs.ropensci.org/spelling/reference/wordlist.html"
+            )
           }
         shell: Rscript {0}
+      
+      - name: Run full spell check using spelling::spell_check_files()
+        if: ${{ inputs.use_full_spell_check }}
+        run: |
+          files <- list.files(
+            ".",
+            recursive = TRUE,
+            full.names = TRUE,
+            pattern = "\\.(cpp|hpp|md|R|Rmd|txt|yml)$"
+          )
+          word_list <- spelling::get_wordlist(".")
+          full_results <- spelling::spell_check_files(
+            files,
+            ignore = word_list
+          )
+          print(full_results)
+          writeLines(
+            as.character(nrow(full_results)),
+            "nrow_results.txt"
+          )
+        shell: Rscript {0}
+
+      - name: Save nrow_results to GITHUB_OUTPUT
+        id: set_output
+        run: |
+          tmp_nrow_results=$(awk '{print int($1)}' nrow_results.txt)
+          echo "nrow_results=$tmp_nrow_results" >> $GITHUB_OUTPUT
+      
+      - name: ⚠️ Report spelling issues as a warning
+        if: ${{ (steps.set_output.outputs.nrow_results > 0) && (inputs.full_check_report_level == 'warning') }}
+        run: |
+          echo "::warning title=Spelling errors were found::Spelling errors were found in the Run full spell check using spelling::spell_check_file() step. Need to ignore some words? Read up on using the WORDLIST file: https://docs.ropensci.org/spelling/reference/wordlist.html"
+
+      - name: ❌ Report spelling issues as an error
+        if: ${{ (steps.set_output.outputs.nrow_results > 0) && (inputs.full_check_report_level == 'error') }}
+        run: |
+          echo "::error title=Spelling errors were found::Spelling errors were found in the Run full spell check using spelling::spell_check_file() step. Need to ignore some words? Read up on using the WORDLIST file: https://docs.ropensci.org/spelling/reference/wordlist.html"
+          exit 1 # This will cause the workflow to fail      
